name: CI/CD Churn Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-churn
          python-version: 3.12.7

      - name: Run Training with MLflow
        working-directory: MLProject
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          python modelling_tuning.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            MLProject/confusion_matrix.png
            MLProject/feature_importance.png
            MLProject/shap_waterfall.png
            MLProject/classification_report.txt
            MLProject/mlruns/

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_SUPERHERP }}
          password: ${{ secrets.DOCKERHUB_SUPERHERP }}

      - name: Build Docker Image
        working-directory: MLProject
        run: |
          MODEL_DIR=$(find mlruns -path "*/artifacts/model" | head -1)
          cp -r "$MODEL_DIR" ./model
          docker build -t ${{ secrets.DOCKERHUB_SUPERHERP }}/churn-model:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_SUPERHERP }}/churn-model:latest