name: CI/CD Churn Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-churn
          python-version: 3.12.7

      - name: Run MLflow Project
        working-directory: MLProject
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          mlflow run .

      - name: Commit and Push Artifacts to GitHub
        run: |
          cp -r MLProject/mlruns .
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add mlruns/
          git commit -m "Save model artifacts from CI"
          git push

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USENAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        working-directory: MLProject
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          MODEL_DIR=$(find mlruns -path "*/artifacts/model" -type d | head -n1)
          if [ -z "$MODEL_DIR" ]; then
            echo "Model not found!"
            ls -la mlruns/
            exit 1
          fi
          echo "Found model at: $MODEL_DIR"
          mlflow models build-docker -m "$MODEL_DIR" -n churn-model

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag churn-model ${{ secrets.DOCKERHUB_USENAME }}/churn-model:latest
          docker push ${{ secrets.DOCKERHUB_USENAME }}/churn-model:latest