name: CI/CD Churn Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12.7
          use-only-tar-bz2: true

      - name: Create conda environment and run MLflow
        run: |
          cd MLProject
          conda env create -f conda.yaml
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate mlflow-churn
          export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
          mkdir -p mlruns
          mlflow experiments create --experiment-name "telecom-churn"
          mlflow run .




      - name: Upload Artifacts (MLflow)
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/**

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image from MLflow Run
        working-directory: MLProject
        run: |
          RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n 1 basename)
          echo "Run ID: $RUN_ID"
          conda activate mlflow-churn
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n churn-model

      - name: Push Docker Image
        run: |
          docker tag churn-model ${{ secrets.DOCKERHUB_USERNAME }}/churn-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-model:latest